### ISSUE TITLE
Question: Connect Clojure REPL?

### ISSUE THREAD

**Issue by teodorlu** [oakes/full-stack-boot-example#3]
Hello!

Thanks for making this example. It's really useful to be able to see what one may end up with without going through a step-by-step tutorial, and not having a huge project to navigate in.

I'm able to connect to the ClojureScript REPL through port 9009 (with `M-x cider-connect-clojurescript`). Do you have a recommended way to connect a Clojure REPL (not ClojureScript)? Should the same port be used, or would that require a different setup / approach?

I realize that you are in no way obliged to give support, but I'd be interested in your opinion!

Kind regards,
Teodor

**Comment by oakes** [comment]
You'll need to run the `repl` task with the `-s` option, which tells it to run an nREPL server. You can either add it to the `run` task or call it directly in your terminal. You can do the latter by running `boot repl -s run`. One of the first things it'll print is "nREPL server started on port..." and then you should be able to just connect to that port number.

**Comment by teodorlu** [comment]
Thanks! I documented what I did in a PR. Feel free to edit, it may be too verbose.
